max_name: 100
languages: {en: "english", vi: "vietnamese", jp: "japanese"}
max_name: 30
min_name: 5
min_password: 6
min_description: 10
max_description: 3000
max_for_limit: 5
per_page: 5
event_truncate: 360
truncate_description: 90
truncate_organization: 30
description_event: 360
max_location: 150
delete: "delete"
comment: "comment"
edit: "edit"
update: "Update"
create: "Create"
per_page_album: 9
per_page_image: 12
per_page_event: 6
new_description: 9
new_content: 9
edit_description: 6
min_rate: 1
max_rate: 5
max_for_rating: 6
round_float: 1
max_show_comment: 5
min_title: 10
new_detail: 100
event_user: 10
event_new: 4
club_member: 6
event_type: 3
min_title: 10
min_content: 10
club_event: 4
event_news: 4
club_member: 6
club_per_page: 6
organization_per_page: 3
my_clubs: "/clubs"
spend: 1
consum: 2
inprocess: "inprocess"
finished: "finished"
event: "Event"
spend_money: 1
none: 0
min_line: 0
max_line: 6
refresh: 60
joined: "joined"
pending: "pending"
reject: "reject"
en: "English"
vi: "Việt Nam"
jp: "日本語"
english: "english"
vietnamese: "vietnamese"
japanese: "japanese"
payment_budget: "Payment For Club Of Month:"
periodic_category: 4
payment_budget: "Payment For Club Of Month:"
max_display_member_club: 5
club_member: 18
notification: 3
get_money: 2
pay_money: 1
event_page: 4
member_manager: 23
notification_event: "Event"
notification_club: "Club"
my_url: "http://club.framgia.vn/"
limit_tags: 4
error_import: "error when input file"
error_data: "has user exist"
read_key_row1: 1
read_data_row2: 2
limit_comments: 7
chat_messages_limit: 30
min_content: 20
ratings: "ratings"
user:
  club_per_page: 6
  avatar_size: 5
  avatar_upload: "image/jpeg,image/gif,image/png"
truncate:
  club:
    description: 100
  album_name: 28
messages_load_more: 30
subsidy: "subsidy"
pay_money: "pay_money"
get_money: "get_money"
max_exspene: 9
tools_url: "https://wsm.framgia.vn/all-tools"
club_description: 200
organization_request:
  max_phone_number_length: 12
  min_phone_number_length: 3
  max_description_length: 1000
  max_name_length: 255
  max_location_length: 255
club_request:
  min_content_length: 10
  max_content_length: 1000
  min_goal_length: 10
  max_goal_length: 1000
  min_rules_length: 10
  max_rules_length: 1000
  min_rule_finance_length: 10
  max_rule_finance_length: 1000
  min_punishment_length: 10
  max_punishment_length: 1000
  max_local_length: 255
  min_plan_length: 10
  max_plan_length: 1000
  max_name_length: 255
  max_member: 1000
  rows_text_area: 10
club:
  min_content_length: 10
  max_content_length: 1000
  min_goal_length: 10
  max_goal_length: 1000
  min_rules_length: 10
  max_rules_length: 1000
  min_rule_finance_length: 10
  max_rule_finance_length: 1000
  min_punishment_length: 10
  max_punishment_length: 1000
  min_plan_length: 10
  max_plan_length: 1000
  max_name_length: 255
  max_member: 1000
  max_content_truncate: 270
  infor: infor
  is_active: 1
  not_active: 0
  image:
    min_width_image_club: 1024
    min_height_image_club: 400
    max_height_image_club: 2000
feed_back:
  min_content: 20
  max_content: 255
days:
  monday: "Monday"
  tuesday: "Tuesday"
  wednesday: "Wednesday"
  thursday: "Thursday"
  friday: "Friday"
  satuday: "Satuday"
  sunday: "Sunday"
sort_clubs: {name_club: "name asc", for_rating: "rating desc", created_at: "created_at desc"}
max_display_image_club: 15
professed: "professed"
hide: "hide"
name_office: " Office"
date_format: "%Y-%m-%d"
date_format_vi: "%d-%m-%Y"
notification_per_page: 25
export_budget:
  bg_title: "F7abce7"
  fg_title: "#FF000000"
  sz_title: 14
  sz_head: 13
  with_colum: 15
export_member:
  bg_title: "F16ecd0"
  fg_title: "#FF000000"
  fg_manager: "Fff5e3a"
  sz_title: 14
  sz_head: 13
  with_colums:
    a: 5
    b: 40
    c: 50
    d: 20
  number: 1
notifications:
  nothing_to_read: 0
  read: "readed"
  un_read: "un_read"
  notification_read: 1
page_member_not_manager: 26
event_notification: "notification"
user_club:
  number: 0
  manager: 1
  member: 0
  join: 1
max_display_member_organization: 10
set_user_donates:
  params_length: 2
  colspan: 5
style_statistic:
  month: "1"
  quarter: "2"
row_email: "Email"
row_name: "Họ và tên"
name_type: 50
club_type_delete: 0
per_page_type: 10
per_page_statistic: 10
moth_statistic: 1
quarter_statistic: 2
colspan_notice_empty: 4
per_page_report: 10
year_ago: 5
per_page_report: 10
style_month: 1
style_quater: 2
namespace_club_manage: "ClubManager"
reject_report: "Reject"
approve_report: "Approve"
notification_report: "StatisticReport"
create_report: "CreateReport"
notification_orgz: "Organization"
update_report: "UpdateReport"
remind_report_month: "RemindReportMonth"
remind_report_quarter: "RemindReportQuarter"
monthly: "monthly"
quarterly: "quarterly"
one: 1
month_per_quarter: 3
file_csv: ".csv"
file_xls: ".xls"
file_xlsx: ".xlsx"
per_page_report_category: 10
obligatory: "obligatory"
max_name_category: 50
count_render_list_report: 1
value_default_check_box: 1
key_date_remind_month: "date_remind_month"
key_date_remind_quarter: "date_remind_quarter"
command_update_whenever: "whenever -w"
size_image_club: 200
action_edit: "edit"
first_range_enum_money_in_report_details: 0
last_range_enum_money_in_report_details: 1
quarter_1: [1,2,3]
quarter_2: [4,5,6]
quarter_3: [7,8,9]
quarter_4: [10,11,12]
